# Generated by Django 4.1.4 on 2023-01-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('preparation', models.BooleanField()),
                ('price', models.FloatField(default=False)),
            ],
        ),
    ]
