# Generated by Django 4.1.4 on 2023-01-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_studies',
            name='preparation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medical_studies',
            name='price',
            field=models.FloatField(),
        ),
    ]
