# Generated by Django 4.1.4 on 2023-02-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_studies', '0002_alter_medical_studies_preparation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical_studies',
            options={'verbose_name': 'Estudio Medico ', 'verbose_name_plural': 'Estudios Medicos'},
        ),
    ]
