# Generated by Django 4.1.4 on 2023-02-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_studies', '0004_medical_studies_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_studies',
            name='Description',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='medical_studies',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medical_studies',
            name='preparation',
            field=models.CharField(max_length=200, verbose_name='Preparacion previa'),
        ),
        migrations.AlterField(
            model_name='medical_studies',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
