# Generated by Django 4.1.4 on 2023-02-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_studies', '0005_alter_medical_studies_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_studies',
            old_name='picture',
            new_name='estpicture',
        ),
    ]
