# Generated by Django 4.1.4 on 2023-02-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Medical_studies', '0006_rename_picture_medical_studies_estpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_studies',
            old_name='estpicture',
            new_name='image',
        ),
    ]
