# Generated by Django 4.1.4 on 2023-02-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconsult', '0003_alter_medical_speciality_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_index', models.ImageField(blank=True, null=True, upload_to='index_images')),
            ],
        ),
    ]
