# Generated by Django 4.1.4 on 2023-02-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconsult', '0006_alter_professionals_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_speciality',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='medical_speciality_images', verbose_name='imagen'),
        ),
    ]
