# Generated by Django 4.1.4 on 2023-02-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appconsult', '0007_medical_speciality_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_speciality',
            old_name='picture',
            new_name='mspicture',
        ),
    ]
